# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.EmailField(max_length=254)),
                ('account_id', models.CharField(default='', max_length=20)),
                ('user_id', models.IntegerField(default=0)),
                ('verification_code', models.IntegerField(default=0)),
                ('delang_contact_id', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('verbiage', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SentMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delang_message_id', models.IntegerField()),
                ('raw_message', models.CharField(max_length=2000)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SunLoanDelangIntegration.Customer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SunLoanDelangIntegration.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_number', models.CharField(default='TEST', max_length=20)),
                ('street', models.CharField(default='TEST', max_length=200)),
                ('state', models.CharField(default='TX', max_length=20)),
                ('zip_code', models.CharField(default='55555', max_length=15)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('api_key', models.CharField(default='8dba905330fa4d5a9b5193c4cedb540c', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='notification_setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SunLoanDelangIntegration.NotificationSetting'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SunLoanDelangIntegration.Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SunLoanDelangIntegration.Store'),
        ),
    ]
